### ISSUE TITLE
Design Check

### ISSUE THREAD

**Issue by philippReist** [philippReist/dancebots_gui#35]
Feedback by Phyllis: Bei Custom Moves finde ich das grün/gelb beisst sich mit dem anderen gelb

**Comment by robinhanhart** [comment]
Possible new color scheme. Make colors more simple. Use yellow to orange tones for "moves" and blue to purple for "lights". Also changed "lights" color to muted blue and dimmed both the timer bars for better visibility.
<img width="1435" alt="color-scheme" src="https://user-images.githubusercontent.com/12276355/73638171-35b8c280-466a-11ea-9cf7-101493d271ee.png">

**Comment by philippReist** [comment]
I like it! Especially that it makes it clearer what is moves and what is lights, and the more muted colors of the timer bars.

I updated all the points above except for tabifying the settings. I can do this until next week and then you can have a final design change? Or you could already implement the changes - just pull develop before changing things on top.

**Comment by philippReist** [comment]
Hi Robin,

Finally, I got around to tabify the settings, see below. You can pull the branch tabifySettings to view the changes and implement the new color scheme: https://github.com/philippReist/dancebots_gui/tree/tabifySettings

Detailed changelist:
- Moved settings background rectangle up to hug radio buttons
- Radio buttons switch border to settings background rectangle color to look like tabs
- Streamlined spacing in settings: All spacings are equal to appWindow.guiMargin now. Same spacing also for custom left/right speed controls, but spacing between L and R is 2x guiMargin.
- Total settings box height is now set automatically so that it fits the largest controls (custom drive), so the heightRatio for primitiveControls could be removed.

Philipp

![image](https://user-images.githubusercontent.com/6594726/74603341-cce23900-50b2-11ea-920c-6d0861f9ca0c.png)

**Comment by robinhanhart** [comment]
Hi

Ich changed some design stuff:

- More spacing under tabs
- Updated color scheme
- Changed styling of vertical titles to match new color scheme and more muted.
- Small change on primitive handles.

![Dancebots-Tabs-Design](https://user-images.githubusercontent.com/12276355/74753367-50955480-5270-11ea-8fca-a787aa8196d1.png)

**Comment by robinhanhart** [comment]
- Handle little rectangle enable opacity
- Fix margin under tabs
- LED Box: Setting do not scale correctly
