### ISSUE TITLE
Pull request build checks seem to not run

### ISSUE THREAD

**Issue by philippReist** [philippReist/dancebots_gui#45]
I made a sample pull request with broken code, and its build tests seem not to be running (I setup the build checks to be a requirement before merging is allowed.

https://github.com/philippReist/dancebots_gui/pull/43

**Comment by ray-hrst** [comment]
@philippReist I set up the build scripts to only run on the master and develop branches. They don't run automatically on any other branch. You can add a specific branch to the build script, see [here](https://github.com/philippReist/dancebots_gui/compare/issue-45#diff-10dc598b293d8d3a66d4d3137386cb44R8). You can see this branch failing appropriately [here](https://github.com/philippReist/dancebots_gui/runs/425271450?check_suite_focus=true) 

I can change the build scripts to run on all branches, but that might get annoying for some developers who push half-finished work to remote (I do that sometimes). Your call.

Alternatively, you can just run the auto build checks before merging devel into master.

**Comment by philippReist** [comment]
Ah I see - running them for just the pull/merge request branches is not possible? I agree doing it for all is not a good option.

**Comment by ray-hrst** [comment]
I don't know what I was thinking lol. Of course that's possible. 
Done!
