### ISSUE TITLE
MacOS Deployment script expects executable name different from build name

### ISSUE THREAD

**Issue by philippReist** [philippReist/dancebots_gui#46]
https://github.com/philippReist/dancebots_gui/blob/develop/gui/mac_os_rc/deploy.sh

Did not work for me without mv-ing the executable from `dancebotsEditor` to `Dancebots Editor`.

Not sure if you will change the build for deploy or want to edit the script to do the mv.

**Comment by ray-hrst** [comment]
This should be resolved with #48. @philippReist please close this issue if/when that PR is merged to devel.

**Comment by philippReist** [comment]
Thanks, Ray!
